version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: appdb
      JWT_SECRET_KEY: supersecret
      CORS_ORIGINS: http://localhost:5173
      INITIAL_ADMIN_EMAIL: admin@example.com
      INITIAL_ADMIN_PASSWORD: admin123
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    working_dir: /app
    image: node:20-alpine
    volumes:
      - ./frontend:/app
    environment:
      VITE_API_BASE: http://localhost:8000
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
